---
abstract: 'Email checking by smtp with Mojo enviroment.'
author:
  - 'Anatoly Y. <snelius@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.52
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-Email-Checker-SMTP
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 5
  Net::DNS: 0.66
resources:
  repository: https://github.com/Snelius30/Mojo-Email-Checker-SMTP
version: 0.02
